name: projectfinal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.2
  bottom_navbar_with_indicator: ^0.0.9
  expansion_tile_card: ^3.0.0
  tiny_charts: ^0.1.0
  syncfusion_flutter_charts: ^26.1.39
  carousel_slider: ^4.2.1
  infinite_carousel: ^1.1.1
  table_calendar: ^3.1.2
  syncfusion_flutter_datepicker: ^26.1.40
  syncfusion_flutter_calendar: ^26.1.40+1
  equatable: ^2.0.5
  get_it: ^7.7.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
 
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 36

flutter:
  uses-material-design: true
  assets:
   - assets\icons\messageicon.png
   - assets/icons/imageicon.png

